version: "3.5"

volumes:
  wiremock-data:
  rabbit-data:

networks:
  parkun:

services:
  parkun_sender:
    container_name: parkun_sender
    networks:
      - parkun
    # image: skaborik/appeal_sender
    build:
        context: ./
        dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    volumes:
      - ${HOME_FOLDER}/logs:/usr/src/app/logs
      - /tmp/temp_files_parkun:/tmp/temp_files_parkun
