version: '3.5'

networks:
  proxynet:
    name: parkun

services:
  sender:
    container_name: parkun_sender
    networks:
      - proxynet
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /tmp/temp_files_parkun:/tmp/temp_files_parkun