version: '3.5'

networks:
  proxynet:
    name: parkun

services:
  browser:
    container_name: parkun_browser
    image: selenium/standalone-firefox:3.141.59
    networks:
      - proxynet
    ports:
      - 4444:4444
    restart: always
    volumes:
      - /dev/shm:/dev/shm
