version: '3.5'

networks:
  proxynet:
    name: parkun

services:
  browser:
    container_name: parkun_browser
    image: selenium/standalone-firefox:3.141.59
    networks:
      - proxynet
    ports:
      - 4444:4444
    restart: always
    volumes:
      - /dev/shm:/dev/shm

  captcha_solver:
    container_name: parkun_captcha_solver
    image: skaborik/solver
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=0
      - 'RUN=flask run --host=0.0.0.0 --port=5000'
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - proxynet
    restart: always
